(function(){
conststatusText=document.getElementById('status-text');

//displayconfiguration/state
window.constants={
timeAxisWidth:150,//note:thesameincss
timestampHeight:20,
timestampTickWidth:10,
channelAxisHeight:32,
channelAxisTickHeight:4,
backgroundColor:'black',
previewHeight:125,
textColor:'lightgray',
lineColor:'lightgray',
separatorLineColor:'#777777',
dotColor:'white',
cpsPlotHeight:300,
cpsExtendRange:0.1,
blurRadius:1,
cursorOffset:3,
};
window.waterfallState={
scale:'sqrt',
palette:'iron',
spectrumBinning:1,
channelBinning:1,
blur:false,
subtractBase:false,
movingAverageVertical:0,
movingAverageHorizontal:0,
maxCpsPercent:100,
minCpsPercent:0,
timeOffsetHours:getLocalTimeOffsetHours(),
previewEnabled:false,
compareCps:false,
channelRange1:[],
channelRange2:[],
spectrumRange:[],
};
window.common={
timeToString:timestamp=>{
constisoFormat=newDate(timestamp+waterfallState.timeOffsetHours*60*60*1000).toISOString();
letoffsetStr;
if(waterfallState.timeOffsetHours>0){
offsetStr='+'+waterfallState.timeOffsetHours+'h';
}elseif(waterfallState.timeOffsetHours<0){
offsetStr=''+waterfallState.timeOffsetHours+'h';
}else{
offsetStr='UTC';
}

returnisoFormat.split('T').join('').split('.')[0]+''+offsetStr;
},
/**
*Convertschannelnumbertoenergyusingcurrentcalibrationforwaterfalldata
*NOTORIGINALWATERFALLDATA,buttheoneafterbinningandothermodifications
*@param{*}channelchannelnumber
*@returnsenergyinkeV
*/
channelToEnergy:channel=>{
returnwaterfallData.baseSpectrum.calibration.reduce((e,c,i)=>e+=Math.pow(channel,i)*c,0);
},
rangeToOriginalRange:(range)=>{
returnexports.rangeToOriginalRange(range,waterfallState.channelBinning/originalWaterfallData.channelBinning);
},
getLocalTimeOffsetHours:()=>getLocalTimeOffsetHours(),
executeWithStatusAsync:(status,func)=>executeWithStatusAsync(status,func),
}

functiongetLocalTimeOffsetHours(){
return-(newDate().getTimezoneOffset()/60);
}

lethideOverlayTimeout=-1;
functionexecuteWithStatusAsync(status,func){
returnnewPromise((res,rej)=>{
setTimeout(()=>{
clearTimeout(hideOverlayTimeout);
statusText.innerText=status;
statusText.style.display='block';
statusText.classList.add('fadein');

setTimeout(()=>{
try{
func();
res();
}catch(e){
rej(e);
}finally{
hideOverlayTimeout=setTimeout(()=>{//debouncetimetoavoidflickering
statusText.innerText='';
statusText.classList.remove('fadein');
statusText.style.display='none';
},250);
}
},25);//letstatustoberendered
},0);
});
}
})();
